### ISSUE TITLE
secp256k1 implementation fails for certain inputs

### ISSUE THREAD

**Issue by haltingstate** [piotrnar/gocoin#15]
copy and past the following unit tests as "misc_tests.go". Into /lib/secp255k1

https://gist.github.com/haltingstate/cf84b5418ac889d192a5

For some valid private keys, the generated public key fails "pubkey2.IsValid()". SIPA's library works for those private keys. A valid public key is not generated for a valid seckey (even through the public key appears to be valid according to sipa's implementation).

About 1 in 1500 keys.

also, for func Multiply(xy, k, out []byte) bool {..}

Multiply(pubkey1, privatekey2) should equal Multiple(pubkey2, privatekey1), fails for these keys.

SIPA said you ported an early version of the library. I cleaned up the library and improved interface, but cannot find the source of these errors.

**Comment by piotrnar** [comment]
Thanks for reporting. I will look into it when I only find some time.

**Comment by piotrnar** [comment]
I fixed it for now, but I did it by analyzing the problem in my code, not by merging all the recent fixes from the original sipa's lib. 

I should review all the changes that have been made in the original lib, ever since the version that my ported lib was based on. But I will need to find much more time for it.

Anyway, the fix for the issue you found is already committed: https://github.com/piotrnar/gocoin/blob/master/lib/secp256k1/xy.go

And thanks so much for reporting this, as it was potentially a very serious one.

**Comment by haltingstate** [comment]
SIPA added very good unit tests. I am porting over unit tests and doing
more tests to compare between the libraries.

**Comment by haltingstate** [comment]
Add 

if pk.IsValid() == false {
	log.Panic()
}

before return in 

func Multiply(xy, k []byte) []byte {

and

func BaseMultiply(k []byte) []byte {

Then try for random input values. I get crash.

**Comment by piotrnar** [comment]
It doesn't matter. 

The "pk" variable is just a temporary.intermediate/internal value inside that functions and IsValid() does not suppose to work on it.
 
If you find place that IsValid() fails on a public key that has been returned from/outside the sec26k1 library, then please let me know.

Cheers

**Comment by piotrnar** [comment]
Sorry. Ignore my previous comment. There is indeed something strange about it - I will have a look at it as soon as possible.

**Comment by piotrnar** [comment]
I was right after all. :)

It works good - nothing is wrong with the returned public key.
Just try this test to see it doesn't fail with "random values":


	package main

	import (
		"github.com/piotrnar/gocoin/lib/secp256k1"
		"crypto/rand"
	)


	func main() {
		var pk [65]byte
		var sec [32]byte
		var out [33]byte
		var cnt uint64
		for {
			rand.Read(sec[:])
			rand.Read(pk[0:33])

			pk[0] = (pk[0]&1) | 2
			if !secp256k1.BaseMultiplyAdd(pk[:33], sec[:], out[:]) {
				println("BaseMultiplyAdd returned error", cnt)
				return
			}

			var pk secp256k1.XY
			if !pk.ParsePubkey(out[:]) {
				println("returned ParsePubkey failed", cnt)
				return
			}


			cnt++
			if (cnt&0xfff)==0 {
				println("cnt", cnt)
			}
		}
	}

**Comment by piotrnar** [comment]
OK - I see what you mean now. :)
Sorry for all the previous, confusing replies.

I think it fails because not any random value can be a valid public key. 
You cannot just take 256 bits of random data and feed it to the function with 02 or 03 in front. Or 512 bits with 04 in front...

If you want to create a random public key, generate 256 bits of random data (that will be your secret key) and then use the function BaseMultiply() to get the public key - this will give you a valid public key that you can pass to BaseMultiplyAdd.

I do not see any problems with BaseMultiply() though - it always returns a valid key:

	package main

	import (
		"github.com/piotrnar/gocoin/lib/secp256k1"
		"encoding/hex"
		"crypto/rand"
	)


	func main() {
		var sec [32]byte
		var out [33]byte
		var cnt uint64
		for {
			rand.Read(sec[:])

			if !secp256k1.BaseMultiply(sec[:], out[:]) {
				println("BaseMultiplyAdd returned error", cnt)
				return
			}

			var pk secp256k1.XY
			if !pk.ParsePubkey(out[:]) {
				println("returned ParsePubkey failed", cnt)
				return
			}

			if !pk.IsValid() {
				println("IsValid failed", cnt, hex.EncodeToString(out[:]))
				return
			}


			cnt++
			if (cnt&0xfff)==0 {
				println("cnt", cnt)
			}
		}
	}

**Comment by haltingstate** [comment]
Yes. That is desired behaviour. It is better that it fails, than people use invalid public key. Feeding in invalid public key can leak bits of private key if used improperly for ECDH, so there is strict verification.
