### ISSUE TITLE
Build fetchbal failed

### ISSUE THREAD

**Issue by selivandex** [piotrnar/gocoin#25]
Hey can't build `fetchbal.go` tool

```bash
selivanov@vs01:~/go/src/github.com/piotrnar/gocoin/tools$ go build fetchbal.go
# command-line-arguments
./fetchbal.go:133: undefined: wallet.NewWallet
```

**Comment by piotrnar** [comment]
Sorry, this one is deprecated. It's been replaced by balio.go
But thank you for reporting - I have removed it from the repo.

**Comment by selivandex** [comment]
I've checked `balio.go` and realized that you use external API service blockr.io But i wondering how can i get balance and transactions list of any address via command line tool using local full node?

**Comment by piotrnar** [comment]
There is no such tool ATM, but if you are familiar with curl or wget, you could get the data via HTTP, assuming you're running WebUI.

In order to do this, you POST the list of addresses (may be just one) you want the check to "/balance.json" and it will return you what you want. Just mind that both the request and the reply are in JSON format.

Run the MakeTx tab on your browser in the developer mode and see the HTTP traffic - it is pretty straight forward.

**Comment by selivandex** [comment]
@piotrnar can i start ./client in background? And make curl requests like 

```bash
curl -X POST http://127.0.0.1:8833/balance.json -d "['1933phfhK3ZgFQNLGSDXvqCn32k2buXY8a']" -H "Content-type: application/json"
```

And also, why it responds with out transactions, where is input ?

**Comment by piotrnar** [comment]
I believe you need to use double quotes, so like:
`curl -X POST http://127.0.0.1:8833/balance.json -d "['1933phfhK3ZgFQNLGSDXvqCn32k2buXY8a']" -H "Content-type: application/json"`

And its the background, use screen. Run the client inside a screen.

**Comment by selivandex** [comment]
@piotrnar and what about transactions? Why there's only outs? i need inputs also :)

**Comment by piotrnar** [comment]
That's more complicated.
There isn't like a single command that gives you a transaction.
At least not yet.
Let me see

**Comment by piotrnar** [comment]
I think ATM the easiest way would be to use the API from WebUI's Wallet page.

See what happens when you click the "balance.zip" link, on Wallet page of the WebUI.

Basically you need to POST the list of addresses that you need the balance for. In response it sends you a zip file containing unspent.txt with the list of txid-vout, plus each tx in a separate binary file.

**Comment by piotrnar** [comment]
OK, I did some change that might me better for you.
When you take the last code, and you call the function like this:
`curl -X POST "http://127.0.0.1:8833/balance.json&rawtx" -d "[\"1933phfhK3ZgFQNLGSDXvqCn32k2buXY8a\"]" -H "Content-type: application/json"`
.. each returned output has additional field "RawTx" that carried the raw transaction.
